### ISSUE TITLE
all: implement RFC 5780 NAT Discovery

### ISSUE THREAD

**Issue by ernado** [gortc/stun#49]
Maybe as "nat" subpackage.

**Comment by songjiayang** [comment]
Is it need stun server to help NAT discovery?

**Comment by ernado** [comment]
@songjiayang yes, the STUN Server need to support RFC 5780 too.
The gortcd currently does not support this.

About the general usage of NAT discovery:
If we can use ICE, the NAT discovery is not needed.

However, it can be used for diagnostics purposes.
E.g. some multiplayer games display NAT Status as "Strict" or "Open" to user a

**Comment by songjiayang** [comment]
Thanks for your explanation.

**Comment by ernado** [comment]
Closing in favour of separate client package.
