### ISSUE TITLE
UDP Question + Proxy Protocol

### ISSUE THREAD

**Issue by 4ydx** [gortc/stun#58]
I hope this question isn't too out of scope, but I didn't see a slack channel etc.

Is it possible to use the proxy protocol in conjunction with udp connections when sending connections through nginx to a stun server?  Is tcp an option?  Or does proxy protocol support need to be added somehow?

**Comment by 4ydx** [comment]
I was trying to put the STUN service behind nginx using udp streaming but i can see that the STUN server returns the ip address of the nginx server itself.  The STUN client's ip address is lost of course.  The only way I know to address this is the proxy protocol.

I could imagine a config option where the STUN server is made aware that incoming connections will have proxy protocol data, but I don't know if just having the original client ip address is enough to fulfill all of the requirements a STUN server is expected to have.

**Comment by ernado** [comment]
I think that putting STUN behind nginx is pointless in general.

Commonly UDP servers are behind L4 load balancers.

Feel free to re-poen that issue if anything specific can be implemented in stun package scope.
