### ISSUE TITLE
What's the relationship with pion/stun

### ISSUE THREAD

**Issue by songjiayang** [gortc/stun#63]
hi @ernado , I find the source code of [pion/stun](https://github.com/pion/stun) is so similar to gortc/stun. Can you tell me what's the relationship between them?  is it to mean that you will  give up maintaining this project and focus on pion/stun.

**Comment by ernado** [comment]
Hi, I've merged gortc/stun to pion/stun and will focus on pion development.

**Comment by songjiayang** [comment]
get it, thanks.
